site_name: audioio

repo_url: https://github.com/bendalab/audioio/

edit_uri: ""

site_author: Benda-Lab

theme: readthedocs
    
nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - API reference: 'api/index.html'
