dist: xenial

language: python

matrix:
    include:
        - python: "3.6"
          os: linux

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - libsndfile1
    - libsndfile1-dev
    - libffi-dev
    - libportaudio2
    - portaudio19-dev
    - osspd

before_install:
  - pip install -U pip

install:
  - pip install numpy
  - pip install scipy
  - pip install wavefile
  - pip install scikits.audiolab
  - pip install git+https://github.com/melizalab/py-ewave
  - pip install sounddevice
  - pip install nose nose-cov
  - pip install codecov
  - pip install -r requirements.txt
  - pip install pdoc3
  - pip install markdown-include
  - pip install mkdocs

script:
  - nosetests -vv --with-coverage --cover-package=audioio
  - ./build-docs.sh

after_success:
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
      branch: master

