name: Run tests
on: [push]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout audioio
        uses: actions/checkout@v2
        
      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          sudo apt install -y libblas-dev liblapack-dev gfortran libsndfile1 libsndfile1-dev libffi-dev ffmpeg libportaudio2 portaudio19-dev osspd libasound2-dev python3-dev
          python -m pip install --upgrade pip
          pip install wavefile
          pip install git+https://github.com/melizalab/py-ewave
          pip install pydub
          pip install pyaudio
          pip install sounddevice
          pip install nose nose-cov
          pip install codecov
          pip install pdoc3
          pip install markdown-include
          pip install mkdocs
          pip install -r requirements.txt

      - name: Run tests
        run: nosetests -vv --with-coverage --cover-package=audioio
        shell: bash

      - name: Build documentation
        run: ./build-docs.sh
        shell: bash
